all: openhttest orderedhttest

openhttest: openhttest.cpp openht.cpp Student.cpp
	g++ -std=c++11 openhttest.cpp openht.cpp Student.cpp -o openhttest
	
orderedhttest: orderedhttest.cpp orderedht.cpp List.cpp
	g++ -std=c++11 orderedhttest.cpp orderedht.cpp List.cpp -o orderedhttest
